# Generated by Django 5.0.1 on 2024-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0002_remove_post_update_date_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('php', 'PHP')], default=None, max_length=40),
        ),
    ]
