# Generated by Django 5.0.1 on 2024-01-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
